### ISSUE TITLE
UnsatisfiedDependencyException: Error creating bean with name 'burpController'

### ISSUE THREAD

**Issue by s-ritik16n** [vmware/burp-rest-api#105]
**Describe the bug**
Not able to run burp-rest-api. What am I doing wrong?

**To Reproduce**
`java -jar burp-rest-api-2.1.0.jar --java.jar=C:\Burp\burpsuite_pro_v2020.4.jar`

**Error Log**

````
2020-04-30 14:31:49.611  INFO 10516 --- [           main] c.vmware.burp.extension.BurpApplication  : Starting BurpApplication on Armor-3-Dev2 with PID 10516 (C:\Burp\burp-rest-api-2.1.0.jar started by Administrator in C:\Burp)
2020-04-30 14:31:49.616  INFO 10516 --- [           main] c.vmware.burp.extension.BurpApplication  : No active profile set, falling back to default profiles: default
2020-04-30 14:31:50.833  INFO 10516 --- [           main] org.eclipse.jetty.util.log               : Logging initialized @2327ms to org.eclipse.jetty.util.log.Slf4jLog
2020-04-30 14:31:51.050  INFO 10516 --- [           main] o.s.b.w.e.j.JettyServletWebServerFactory : Server initialized with port: 8090
2020-04-30 14:31:51.055  INFO 10516 --- [           main] org.eclipse.jetty.server.Server          : jetty-9.4.27.v20200227; built: 2020-02-27T18:37:21.340Z; git: a304fd9f351f337e7c0e2a7c28878dd536149c6c; jvm 13.0.1+9
2020-04-30 14:31:51.077  INFO 10516 --- [           main] o.e.j.s.h.ContextHandler.application     : Initializing Spring embedded WebApplicationContext
2020-04-30 14:31:51.078  INFO 10516 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1407 ms
2020-04-30 14:31:51.218  INFO 10516 --- [           main] org.eclipse.jetty.server.session         : DefaultSessionIdManager workerName=node0
2020-04-30 14:31:51.219  INFO 10516 --- [           main] org.eclipse.jetty.server.session         : No SessionScavenger set, using defaults
2020-04-30 14:31:51.225  INFO 10516 --- [           main] org.eclipse.jetty.server.session         : node0 Scavenging every 660000ms
2020-04-30 14:31:51.233  INFO 10516 --- [           main] o.e.jetty.server.handler.ContextHandler  : Started o.s.b.w.e.j.JettyEmbeddedWebAppContext@7e5c856f{application,/,[file:///C:/Users/Administrator/AppData/Local/Temp/2/jetty-docbase.6483796072049025508.8090/, jar:file:/C:/Burp/burp-rest-api-2.1.0.jar!/BOOT-INF/lib/springfox-swagger-ui-2.9.2.jar!/META-INF/resources],AVAILABLE}
2020-04-30 14:31:51.235  INFO 10516 --- [           main] org.eclipse.jetty.server.Server          : Started @2731ms
2020-04-30 14:31:51.280  INFO 10516 --- [           main] c.v.burp.extension.service.BurpService   : # of command line arguments received to Burp suite: 1
2020-04-30 14:31:51.281  INFO 10516 --- [           main] c.v.burp.extension.service.BurpService   : Launching Burp suite in headless mode...
2020-04-30 14:31:51.632  INFO 10516 --- [           main] c.v.burp.extension.service.BurpService   : Launching the Burp with options: [--java.jar=C:\Burp\burpsuite_pro_v2020.4.jar, --project-file=<path>.burp, --config-file=<path>.json, --user-config-file=<path>.json]
2020-04-30 14:31:51.634  WARN 10516 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'burpController': Unsatisfied dependency expressed through field 'burp'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'burpService' defined in URL [jar:file:/C:/Burp/burp-rest-api-2.1.0.jar!/BOOT-INF/classes!/com/vmware/burp/extension/service/BurpService.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.vmware.burp.extension.service.BurpService]: Constructor threw exception; nested exception is java.lang.ClassNotFoundException: burp.StartBurp
2020-04-30 14:31:51.644  INFO 10516 --- [           main] org.eclipse.jetty.server.session         : node0 Stopped scavenging
2020-04-30 14:31:51.647  INFO 10516 --- [           main] o.e.jetty.server.handler.ContextHandler  : Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@7e5c856f{application,/,[file:///C:/Users/Administrator/AppData/Local/Temp/2/jetty-docbase.6483796072049025508.8090/, jar:file:/C:/Burp/burp-rest-api-2.1.0.jar!/BOOT-INF/lib/springfox-swagger-ui-2.9.2.jar!/META-INF/resources],UNAVAILABLE}
2020-04-30 14:31:51.664  INFO 10516 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-04-30 14:31:51.670 ERROR 10516 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'burpController': Unsatisfied dependency expressed through field 'burp'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'burpService' defined in URL [jar:file:/C:/Burp/burp-rest-api-2.1.0.jar!/BOOT-INF/classes!/com/vmware/burp/extension/service/BurpService.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.vmware.burp.extension.service.BurpService]: Constructor threw exception; nested exception is java.lang.ClassNotFoundException: burp.StartBurp
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:882) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]
        at com.vmware.burp.extension.BurpApplication.main(BurpApplication.java:18) ~[classes!/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:567) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[burp-rest-api-2.1.0.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[burp-rest-api-2.1.0.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) ~[burp-rest-api-2.1.0.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) ~[burp-rest-api-2.1.0.jar:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'burpService' defined in URL [jar:file:/C:/Burp/burp-rest-api-2.1.0.jar!/BOOT-INF/classes!/com/vmware/burp/extension/service/BurpService.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.vmware.burp.extension.service.BurpService]: Constructor threw exception; nested exception is java.lang.ClassNotFoundException: burp.StartBurp
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:314) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:295) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1290) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1210) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        ... 25 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.vmware.burp.extension.service.BurpService]: Constructor threw exception; nested exception is java.lang.ClassNotFoundException: burp.StartBurp
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:217) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:310) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        ... 38 common frames omitted
Caused by: java.lang.ClassNotFoundException: burp.StartBurp
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[na:na]
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92) ~[burp-rest-api-2.1.0.jar:na]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
        at com.vmware.burp.extension.service.BurpService.<init>(BurpService.java:135) ~[classes!/:na]
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[na:na]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[na:na]
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:204) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        ... 40 common frames omitted

````

**Desktop (please complete the following information):**
- OS: Windows
- burpsuite_pro_v2020.4
- burp-rest-api-2.1.0.jar

**Comment by ikkisoft** [comment]
As mentioned in the latest README - https://github.com/vmware/burp-rest-api/blob/master/README.md, for newer Java versions you have to execute the software using the launcher script:

```
./burp-rest-api.bat
```

Make sure to have  the original Burp Suite JAR within the same directory.
