### ISSUE TITLE
Cannot start the application 

### ISSUE THREAD

**Issue by KamiShire** [vmware/burp-rest-api#119]
I receive `java.lang.ClassNotFoundException: burp.StartBurp` on start up.

**To Reproduce**
1. launch burp-rest-api.bat

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64 bit
 - Burp Suite _Professional_ v2020.9.2
 - Extension **burp-rest-api** version: 2.1.0
 - Java version: openjdk version "11.0.5" 2019-10-15 LTS
 OpenJDK Runtime Environment Corretto-11.0.5.10.1 (build 11.0.5+10-LTS)
 OpenJDK 64-Bit Server VM Corretto-11.0.5.10.1 (build 11.0.5+10-LTS, mixed mode)

**Additional notes** 
I have a folder containing only:
- burp-rest-api.bat
- burp-rest-api-2.1.0.jar
- burpsuite_pro_v2020.9.2.jar

**Log**
```
2020-10-28 16:48:57.659  INFO 27832 --- [           main] c.vmware.burp.extension.BurpApplication  : Starting BurpApplication on PC0120 with PID 27832 (D:\Sviluppo\Programmi\BurpRestApi\burp-rest-api-2.1.0.jar started by mattia.bolzonella in D:\Sviluppo\Programmi\BurpRestApi)
2020-10-28 16:48:57.663  INFO 27832 --- [           main] c.vmware.burp.extension.BurpApplication  : No active profile set, falling back to default profiles: default
2020-10-28 16:48:58.808  INFO 27832 --- [           main] org.eclipse.jetty.util.log               : Logging initialized @2229ms to org.eclipse.jetty.util.log.Slf4jLog
2020-10-28 16:49:00.966  INFO 27832 --- [           main] o.s.b.w.e.j.JettyServletWebServerFactory : Server initialized with port: 8090
2020-10-28 16:49:00.970  INFO 27832 --- [           main] org.eclipse.jetty.server.Server          : jetty-9.4.27.v20200227; built: 2020-02-27T18:37:21.340Z; git: a304fd9f351f337e7c0e2a7c28878dd536149c6c; jvm 11.0.5+10-LTS
2020-10-28 16:49:01.004  INFO 27832 --- [           main] o.e.j.s.h.ContextHandler.application     : Initializing Spring embedded WebApplicationContext
2020-10-28 16:49:01.005  INFO 27832 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 3289 ms
2020-10-28 16:49:01.131  INFO 27832 --- [           main] org.eclipse.jetty.server.session         : DefaultSessionIdManager workerName=node0
2020-10-28 16:49:01.131  INFO 27832 --- [           main] org.eclipse.jetty.server.session         : No SessionScavenger set, using defaults
2020-10-28 16:49:01.135  INFO 27832 --- [           main] org.eclipse.jetty.server.session         : node0 Scavenging every 660000ms
2020-10-28 16:49:01.141  INFO 27832 --- [           main] o.e.jetty.server.handler.ContextHandler  : Started o.s.b.w.e.j.JettyEmbeddedWebAppContext@784b990c{application,/,[file:///C:/Users/mattia.bolzonella/AppData/Local/Temp/jetty-docbase.9175172388681680356.8090/, jar:file:/D:/Sviluppo/Programmi/BurpRestApi/burp-rest-api-2.1.0.jar!/BOOT-INF/lib/springfox-swagger-ui-2.9.2.jar!/META-INF/resources],AVAILABLE}
2020-10-28 16:49:01.142  INFO 27832 --- [           main] org.eclipse.jetty.server.Server          : Started @4564ms
2020-10-28 16:49:01.182  INFO 27832 --- [           main] c.v.burp.extension.service.BurpService   : # of command line arguments received to Burp suite: 0
2020-10-28 16:49:01.182  INFO 27832 --- [           main] c.v.burp.extension.service.BurpService   : Launching Burp suite in headless mode...
2020-10-28 16:49:01.465  INFO 27832 --- [           main] c.v.burp.extension.service.BurpService   : Launching the Burp with options: [--project-file=C:\Users\MATTIA~1.BOL\AppData\Local\Temp\temp-project-dir-3188493647918416933\temp-project.burp, --config-file=C:\Users\MATTIA~1.BOL\AppData\Local\Temp\project-options9058321703039456663.json, --user-config-file=C:\Users\MATTIA~1.BOL\AppData\Local\Temp\user-options_13113431379704714113.json]
2020-10-28 16:49:01.466  WARN 27832 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'burpController': Unsatisfied dependency expressed through field 'burp'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'burpService' defined in URL [jar:file:/D:/Sviluppo/Programmi/BurpRestApi/burp-rest-api-2.1.0.jar!/BOOT-INF/classes!/com/vmware/burp/extension/service/BurpService.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.vmware.burp.extension.service.BurpService]: Constructor threw exception; nested exception is java.lang.ClassNotFoundException: burp.StartBurp
2020-10-28 16:49:01.471  INFO 27832 --- [           main] org.eclipse.jetty.server.session         : node0 Stopped scavenging
2020-10-28 16:49:01.473  INFO 27832 --- [           main] o.e.jetty.server.handler.ContextHandler  : Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@784b990c{application,/,[file:///C:/Users/mattia.bolzonella/AppData/Local/Temp/jetty-docbase.9175172388681680356.8090/, jar:file:/D:/Sviluppo/Programmi/BurpRestApi/burp-rest-api-2.1.0.jar!/BOOT-INF/lib/springfox-swagger-ui-2.9.2.jar!/META-INF/resources],UNAVAILABLE}
2020-10-28 16:49:01.479  INFO 27832 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-10-28 16:49:01.486 ERROR 27832 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'burpController': Unsatisfied dependency expressed through field 'burp'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'burpService' defined in URL [jar:file:/D:/Sviluppo/Programmi/BurpRestApi/burp-rest-api-2.1.0.jar!/BOOT-INF/classes!/com/vmware/burp/extension/service/BurpService.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.vmware.burp.extension.service.BurpService]: Constructor threw exception; nested exception is java.lang.ClassNotFoundException: burp.StartBurp
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:882) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]
        at com.vmware.burp.extension.BurpApplication.main(BurpApplication.java:18) ~[classes!/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[burp-rest-api-2.1.0.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[burp-rest-api-2.1.0.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) ~[burp-rest-api-2.1.0.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) ~[burp-rest-api-2.1.0.jar:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'burpService' defined in URL [jar:file:/D:/Sviluppo/Programmi/BurpRestApi/burp-rest-api-2.1.0.jar!/BOOT-INF/classes!/com/vmware/burp/extension/service/BurpService.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.vmware.burp.extension.service.BurpService]: Constructor threw exception; nested exception is java.lang.ClassNotFoundException: burp.StartBurp
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:314) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:295) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1290) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1210) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        ... 25 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.vmware.burp.extension.service.BurpService]: Constructor threw exception; nested exception is java.lang.ClassNotFoundException: burp.StartBurp
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:217) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:310) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        ... 38 common frames omitted
Caused by: java.lang.ClassNotFoundException: burp.StartBurp
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[na:na]
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92) ~[burp-rest-api-2.1.0.jar:na]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
        at com.vmware.burp.extension.service.BurpService.<init>(BurpService.java:135) ~[classes!/:na]
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[na:na]
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:204) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        ... 40 common frames omitted

```

**Comment by rajesh0411** [comment]
Facing the same issue with JAVA 8

**Comment by hupling** [comment]
Maybe you should rename `burpsuite_pro_v2020.9.2.jar` to `burpsuite_pro.jar`

**Comment by tomaszdoyensec** [comment]
> Additional notes
> I have a folder containing only:
> 
> burp-rest-api.bat
> burp-rest-api-2.1.0.jar
> burpsuite_pro_v2020.9.2.jar

Hey @KamiShire did you considered to rename burpsuite_pro_v2020.9.2.jar to burpsuite_pro.jar ? Seems like the problem lies here.

**Comment by ikkisoft** [comment]
No updates since Dec 2020. Please re-open if you're facing the same problem again.

**Comment by choua013** [comment]
I am getting the same error mentioned above when trying to start the application.

Desktop:

OS: Windows 10 Enterprise 64 bit
Burp Suite Professional v2021.8.2
Extension burp-rest-api version: 2.1.0
Java version: 16.0.1 (Oracle)

Additional notes
I have a folder containing only:

burp-rest-api.sh
burp-rest-api.bat
burp-rest-api-2.1.0.jar
burpsuite_pro.jar

I am able to run in headless mode when using the jar file provided by PortSwigger (the developers of Burp) but when using this jar file, I get the same error mentioned above.

Any help would be much appreciated, thanks

**Comment by vinilnarayan** [comment]
Hi @ikkisoft,
I'm getting the same error when I start with Jenkins + ANT Script. But no issue to start with CLI commands (_./ant -f /home/A-7280/Documents/Build.xml_).

Below are my ant script and corresponding log has been attached. [attached.]([JenkinsLog.txt](https://github.com/vmware/burp-rest-api/files/9028608/JenkinsLog.txt))

_<project name="devSecOps" default="StartBurp">
    <target name="StartBurp">
        <exec executable="/bin/bash" dir="/home/A-7280/Documents/BurpSuiteProfessional">
            
            <arg value="burp-rest-api.sh"/>
            <arg value="--headless.mode=false"/>
            <arg value="--config-file=/home/A-7280/Documents/BurpOptions/ProjectOptions_Extenders.json"/>
            <arg value="--user-config-file=/home/A-7280/Documents/BurpOptions/UserOptions_Extenders.json"/>
        </exec>
    </target>
</project>_

**Comment by hupling** [comment]
Your Java Version is wrong:
```
[exec] Caused by: java.lang.UnsupportedClassVersionError: burp/StartBurp has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```
