### ISSUE TITLE
Failed to Restore state

### ISSUE THREAD

**Issue by dwareddy** [vmware/burp-rest-api#15]
Added saved state file in the path "../../src/main/resources/cleanstate/" and triggered reset method but it is throwing "Internal Server Error". here is the log displayed on the console. state, json and burp files tried for this exercise but no luck.

2017-07-28 01:50:02.792  INFO 2204 --- [nio-8090-exec-7] c.v.burp.extension.service.BurpService   : Restoring state by replacing state with a new state
2017-07-28 01:50:02.793 ERROR 2204 --- [nio-8090-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context
 with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: An error occurred during r
estore operation] with root cause

java.lang.RuntimeException: java.lang.RuntimeException: An error occurred during restore operation
        at burp.fwe.a(Unknown Source) ~[burpsuite_pro.jar:na]
        at burp.ar.restoreState(Unknown Source) ~[burpsuite_pro.jar:na]
        at com.vmware.burp.extension.service.BurpService.restoreState(BurpService.java:244) ~[main/:na]
        at com.vmware.burp.extension.web.BurpController.resetState(BurpController.java:337) ~[main/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222) ~[spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]

**Comment by 0x4D31** [comment]
I also get the same error when I want to Reset State

**Comment by act1on3** [comment]
I also get same error.
burp_suite_pro_v1.7.23

**Comment by milo2012** [comment]
It seems like in line 331 of https://github.com/vmware/burp-rest-api/blob/0174a49e53bd77e34ab01533b31b219d3d1988d8/src/main/java/com/vmware/burp/extension/web/BurpController.java, it is looking for the file 'cleanstate', if you save an 'empty' state via Burp and put the file in the below location, the issue will be fixed.

Hope that helps.

335      File emptyState = new File("../../src/main/resources/cleanstate");
336	      burp.restoreState(emptyState);
337	      log.info("Burp state is reset to clean");

**Comment by gangelino** [comment]
Fixed by https://github.com/vmware/burp-rest-api/pull/28
