### ISSUE TITLE
Extensions

### ISSUE THREAD

**Issue by act1on3** [vmware/burp-rest-api#25]
Hi!
I have problems with using extensions.
Burp version `1.7.27`
If I launch jar with UI:
`java -jar burp-rest-api.jar --headless.mode=false`
No one extensions doesn't work with error:
```
java.lang.Exception: Extension does not implement any usable methods
	at burp.eqh.<init>(Unknown Source)
	at burp.b0g.a(Unknown Source)
	at burp.kpe.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
```
If I launch from gradle:
`./gradlew bootRun -Djava.awt.headless=false`
got errors:
* with extension [Backslash Powered Scanner](https://portswigger.net/bappstore/9cff8c55432a45808432e26dbb2b41d8)
```
This extension requires Burp Suite Pro 1.7.10 or later
java.lang.NoSuchMethodError
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at burp.mch.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)

```

* with extension [Additional Scanner Checks](https://portswigger.net/bappstore/a158fd3fc9394253be3aa0bc4c181d1f)
```
java.lang.IllegalArgumentException: Cannot create PyString with non-byte value
	at org.python.core.PyString.<init>(PyString.java:64)
	at org.python.core.PyString.<init>(PyString.java:70)
	at org.python.core.Py.newString(Py.java:641)
	at org.python.core.PySystemState.initRegistry(PySystemState.java:800)
	at org.python.core.PySystemState.doInitialize(PySystemState.java:1045)
	at org.python.core.PySystemState.initialize(PySystemState.java:974)
	at org.python.core.PySystemState.initialize(PySystemState.java:930)
	at org.python.core.PySystemState.initialize(PySystemState.java:925)
	at org.python.core.PySystemState.initialize(PySystemState.java:920)
	at org.python.core.PySystemState.initialize(PySystemState.java:916)
	at org.python.core.ThreadStateMapping.getThreadState(ThreadStateMapping.java:32)
	at org.python.core.Py.getThreadState(Py.java:1440)
	at org.python.core.Py.getThreadState(Py.java:1436)
	at org.python.core.Py.getSystemState(Py.java:1456)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:105)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:94)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:71)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at burp.gqh.<init>(Unknown Source)
	at burp.b0g.a(Unknown Source)
	at burp.kpe.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
```
path to jython is correct.

**Comment by act1on3** [comment]
Sorry, all is ok:)
Real problem is extensions working only using build `./gradlew bootRun`
**Extensions not work with jar** `java -jar burp-rest-api.jar` :(

My experience:
* with gui `./gradlew bootRun -Djava.awt.headless=false` **extensions do not load  automatically**.
* you can not configurate extensions over method `PUT /burp/configuration`
* you can not understand extensions are working or not while you will get report from scan (issues). In the report will be issues that generated by extensions.

**Comment by ikkisoft** [comment]
The issue with extensions is that _burp-rest-api_ is currently loaded as a _legacy extension_, thus it's not possible to load additional extensions. 

In general, it's possible to load extensions using a custom _user-project-file_ containing:

```
"extender":{
            "extensions":[
                {
                    "errors":"ui",
                    "extension_file":"PATH OF THE JAR",
                    "extension_type":"java",
                    "loaded":true,
                    "name":"DetectELJ",
                    "output":"ui"
                }
            ],
```
However, this will not work with the current implementation.

If anyone has an idea on how to implement a generic solution, please let me know - I would be happy to implement it.

**Comment by henshin** [comment]
According to Burp tech support, this happens because this extension is being loaded through the classpath when Burp is loading. 
The solution would be to compile this extension as a standalone jar using the normal extension format and then load it in Burp, exit and then start Burp again with necessary extension command line options.
This was the solution implemented for the Carbonator extension. I suggest looking at their source code.

**Comment by henshin** [comment]
Not sure if helps, but I was able to compile the plugin as a standalone extension using the following pom.xml and compiling using maven:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>burp-rest-api</groupId>
  <artifactId>burp-rest-api</artifactId>
  <version>1.0.3</version>
  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-jetty</artifactId>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <artifactId>commons-logging</artifactId>
          <groupId>commons-logging</groupId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>burpsuite_pro</groupId>
      <version>1.0</version>
      <artifactId>burpsuite_pro</artifactId>
      <scope>system</scope>
      <systemPath>/path/to/burp-rest-api/lib/burpsuite_pro.jar</systemPath>
      <exclusions>
        <exclusion>
          <artifactId>commons-logging</artifactId>
          <groupId>commons-logging</groupId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <version>1.7.25</version>
      <artifactId>slf4j-api</artifactId>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <artifactId>commons-logging</artifactId>
          <groupId>commons-logging</groupId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>io.springfox</groupId>
      <artifactId>springfox-swagger2</artifactId>
      <version>2.1.0</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <artifactId>commons-logging</artifactId>
          <groupId>commons-logging</groupId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.apache.httpcomponents</groupId>
      <artifactId>httpclient</artifactId>
      <version>4.5.2</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.springfox</groupId>
      <artifactId>springfox-swagger-ui</artifactId>
      <version>2.1.0</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <artifactId>commons-logging</artifactId>
          <groupId>commons-logging</groupId>
        </exclusion>
      </exclusions>
    </dependency>
  </dependencies>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.3.2.RELEASE</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <configuration>
          <archive>
            <manifest>
              <addClasspath>true</addClasspath>
            </manifest>
          </archive>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-assembly-plugin</artifactId>
        <configuration>
          <descriptorRefs>
            <descriptorRef>jar-with-dependencies</descriptorRef>
          </descriptorRefs>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>2.3.1</version>
        <configuration>
          <archive/>
          <source>1.8</source>
          <target>1.8</target>
          <descriptorRefs>
            <descriptorRef>jar-with-dependencies</descriptorRef>
          </descriptorRefs>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
```
I'm not a developer so this pom.xml is probably not very well formatted.
Then using maven like:
```
mvn clean compile assembly:single
```
This creates the file `burp-rest-api-1.0.3-jar-with-dependencies.jar` in the `target` folder.

Even though I can load the jar in Burp, I'm not sure how could I use the features afterwards. The API server doesn't launch when I load the extension.

**Comment by lestatk0** [comment]
I have the same issue. It looks that Python's extensions work correctly, but at the same time java's extensions don't work.
in a user-config-file i have  
  `{
                    "errors":"ui",
                    "extension_file":"/opt/burp-ext/J2EEScan-1.2.5-jar-with-dependencies.jar",
                    "extension_type":"java",
                    "loaded":true,
                    "name":"J2EE Advanced Tests",
                    "output":"ui"
                },`
