### ISSUE TITLE
Build is failing with BurpSuitePro 1.7.31

### ISSUE THREAD

**Issue by ajinabraham** [vmware/burp-rest-api#27]
Using BurpSuitePro 1.7.31
```
Failed tests
BurpClientIT. testGetProxyHistoryAndSiteMap
BurpClientIT. testScannerSpiderAndReportMethods
```
```
c$ ./gradlew clean build
:clean
:createschemaTargetDir UP-TO-DATE
:compileJava
Note: /Users/<>/Code/burp-rest-api/src/main/java/com/vmware/burp/extension/service/BurpService.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:processResources
:classes
:findMainClass
:jar
:bootRepackage
:assemble
:compileTestJava
:processTestResources UP-TO-DATE
:testClasses
:test

com.vmware.burp.extension.client.BurpClientIT > testConfigMethods FAILED
    org.springframework.web.client.HttpServerErrorException at BurpClientIT.java:88

com.vmware.burp.extension.client.BurpClientIT > testGetProxyHistoryAndSiteMap FAILED
    javax.net.ssl.SSLHandshakeException at BurpClientIT.java:199
        Caused by: sun.security.validator.ValidatorException at BurpClientIT.java:199
            Caused by: sun.security.provider.certpath.SunCertPathBuilderException at BurpClientIT.java:199

com.vmware.burp.extension.client.BurpClientIT > testScannerSpiderAndReportMethods FAILED
    javax.net.ssl.SSLHandshakeException at BurpClientIT.java:199
        Caused by: sun.security.validator.ValidatorException at BurpClientIT.java:199
            Caused by: sun.security.provider.certpath.SunCertPathBuilderException at BurpClientIT.java:199
2018-01-30 01:11:45.480  INFO 2857 --- [       Thread-7] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@451f19b8: startup date [Tue Jan 30 01:11:24 IST 2018]; root of context hierarchy
2018-01-30 01:11:45.485  INFO 2857 --- [       Thread-7] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 2147483647

5 tests completed, 3 failed
:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///Users/<>/Code/burp-rest-api/build/reports/tests/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by gangelino** [comment]
Can you try again now that this commit has been merged?
https://github.com/vmware/burp-rest-api/commit/30b0a51eca2744b927e321a41e8e610e2bd4c1fb

**Comment by ikkisoft** [comment]
This should be fixed with the latest commit.

**Comment by ajinabraham** [comment]
This is what  I got with latest master

```
com.vmware.burp.extension.client.BurpClientIT > testGetProxyHistoryAndSiteMap FAILED
    java.lang.AssertionError at BurpClientIT.java:100
2018-02-22 10:45:13.760  INFO 97883 --- [      Thread-16] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@21699c38: startup date [Thu Feb 22 10:44:52 IST 2018]; root of context hierarchy
2018-02-22 10:45:13.764  INFO 97883 --- [      Thread-16] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 2147483647
2018-02-22 10:45:13.780  INFO 97883 --- [      Thread-16] o.eclipse.jetty.server.ServerConnector   : Stopped ServerConnector@183d5a79{HTTP/1.1}{0.0.0.0:8090}
2018-02-22 10:45:13.782  INFO 97883 --- [      Thread-16] application                              : Destroying Spring FrameworkServlet 'dispatcherServlet'
2018-02-22 10:45:13.783  INFO 97883 --- [      Thread-16] o.e.jetty.server.handler.ContextHandler  : Stopped o.s.b.c.e.j.JettyEmbeddedWebAppContext@123da718{/,file:/private/var/folders/1x/4ltqfp5d20lfh58dt104fc0h0000gn/T/jetty-docbase.5468664182128965444.8090/,UNAVAILABLE}

4 tests completed, 1 failed
:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///Users/<>/burp-rest-api/build/reports/tests/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 7.817 secs
```

**Comment by ajinabraham** [comment]
From the html report
```
testGetProxyHistoryAndSiteMap
java.lang.AssertionError: expected:<2> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.vmware.burp.extension.client.BurpClientIT.testGetProxyHistoryAndSiteMap(BurpClientIT.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:254)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:89)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:193)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:112)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:56)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:364)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ikkisoft** [comment]
It appears that the proxy wasn't running (e.g. another Burp instance open?) or maybe user-options that were previously configured manually in Burp are changing the setup. I will push another PR soon to mitigate the potential user-options override. 

I would suggest to open Burp manually and make sure that everything works. Then, shutdown all Java processes and try again to build.

**Comment by ajinabraham** [comment]
Oh yes, I was running burp suite while building. The build is successful now.

**Comment by ikkisoft** [comment]
Great - this issue can be closed. cc: @gangelino
